version: "2.0" # docker compose 파일의 버전

services: # 아래는 서비스 정의  
   python-app: # services명  
      build: ./dir      # Dockerfile의 경로 
      stdin_open: true         # i
      tty: true                # t
      command: /bin/bash       # 컨테이너 실행 후 bash 셸로 접속